block.settings.related_contents_block:
  type: block_settings
  label: 'Related contents block settings'
  mapping:
    content_type:
      type: string
      label: 'The name of the content type to display'
    relationship_field:
      type: string
      label: 'The relationship field name to bind related contents'
    max_number:
      type: integer
      label: 'Max number of contents to display'

content_publishing_job.publishing_config.settings:
  type: config_entity
  label: 'Publishing configuration for contents'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    content_type:
      type: string
      label: 'Name of the content type'
    date_field:
      type: string
      label: 'Name of the date field'
